POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "ola",
    "author": "shirubaarison",
    "url": "dkakd.com",
    "likes": 0,
    "userId": "65b572795cf54d776276a7ee"
}