POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pbGVpIiwiaWQiOiI2NWI2NThiOTk2ZDdkY2Y4OTg5ZWFmNDIiLCJpYXQiOjE3MDY0NjY4NDZ9.tU7Hre8Gm10AsTXsMlFP1K-9zHODgoTy8z0D42MPIOc

{
    "title": "seraq2",
    "author": "barack obama",
    "url": "http://dkakd.com",
    "likes": 100000,
    "userId": "65b572795cf54d776276a7ee"
}