DELETE http://localhost:3001/api/blogs/65b6c8f2d2485f842e16cc74
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJpbGRpYW4iLCJpZCI6IjY1YjZjN2QyMDA5YWIyNmQ4YWIyNmI0OSIsImlhdCI6MTcwNjQ3NzY1MSwiZXhwIjoxNzA2NDgxMjUxfQ.zwnuftVEh5gAuvrSsIQokZuMeleJhOWle8eSqYj_0Bg